version: "3.7"
services:
  app:
    build:
      args:
        user: satya
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: digilib
    container_name: digilib-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - digilib

  db:
    image: mysql:8.0
    container_name: digilib-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - digilib

  nginx:
    image: nginx:1.17-alpine
    container_name: digilib-nginx
    restart: unless-stopped
    ports:
      - 8002:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - digilib

volumes:
  dbdata:
    driver: local

networks:
  digilib:
    driver: bridge